config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :movies
  resources :crawls

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
	belongs_to :character
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
	has_and_belongs_to_many :movies
	has_many :actors
end

app/models/crawl.rb
class Crawl < ApplicationRecord
	belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord

	def display_name
    	"#{title}"
 	 end

	validates :title, presence: true,
                   	  length: { minimum: 5 }

	has_one :crawl
	has_and_belongs_to_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # def hello
  # 	render text: "Star Wars Info"
  # end

end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController

	def index
		@crawls = Crawl.order(:movie_id)
	end

	def show
		@crawl = Crawl.find(params[:id])
	end

	def new
		@crawl = Crawl.new
	end

	def edit
		@crawl = Crawl.find(params[:id])
	end

	def create
		@crawl = Crawl.new(movie_params)

		if @crawl.save
		 	redirect_to @crawl
		else
			render 'new'
		end
	end

	def update
		@crawl = Crawl.find(params[:id])

		if @crawl.update(crawl_params)
			redirect_to @crawl
		else
			render 'edit'
		end
	end

	def destroy
		@crawl = Crawl.find(params[:id])
		@crawl.destroy

		redirect_to crawls_path
	end


	private

	def crawl_params
		params.require(:crawl).permit(:text, :movie_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.order(:order)
	end

	def show
		@movie = Movie.find(params[:id])
	end

	def new
		@movie = Movie.new
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def create
		@movie = Movie.new(movie_params)

		if @movie.save
		 	redirect_to @movie
		else
			render 'new'
		end
	end

	def update
		@movie = Movie.find(params[:id])

		if @movie.update(movie_params)
			redirect_to @movie
		else
			render 'edit'
		end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy

		redirect_to movies_path
	end


	private

	def movie_params
		params.require(:movie).permit(:title, :release_date, :order, :length, :crawl_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawls_helper.rb
module CrawlsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/crawls/_form.html.erb
<%= form_with model: @crawl, local: true do |form| %>

  <% if @crawl.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@crawl.errors.count, "error") %> prohibited
        this crawl from being saved:
      </h2>
      <ul>
        <% @crawl.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :movie_id %><br>
    <%= form.collection_select :movie_id, Movie.all, :id, :display_name %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/crawls/edit.html.erb
<%= link_to '<< All Crawls', crawls_path %>

<h1>Edit</h1>

<%= render 'form' %>

app/views/crawls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Star Wars Crawls</h1>

<%= link_to 'Add New Crawl', new_crawl_path %>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @crawls.each do |crawl| %>
      <tr>
        <td><%= crawl.movie.display_name %></td>
        <td></td>
        <td><%= link_to 'View', crawl %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', controller: 'home' %>

app/views/crawls/new.html.erb
<%= link_to '<< Back', crawls_path %>

<h1>New Crawl</h1>

<%= render 'form' %>

app/views/crawls/show.html.erb
<%= link_to '<< All Crawls', crawls_path %>

<h2>
  <%= @crawl.movie.display_name %>
</h2>
 
<p>
  <%= @crawl.text %>
</p>

<%= link_to 'Edit', edit_crawl_path(@crawl) %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Star Wars</h1>

<%= link_to 'Movies', controller: 'movies' %>
<%= link_to 'Crawls', controller: 'crawls' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starwars</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: @movie, local: true do |form| %>

  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@movie.errors.count, "error") %> prohibited
        this movie from being saved:
      </h2>
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :release_date, 'Release Date' %><br>
    <%= form.date_field :release_date %>
  </p>

  <p>
    <%= form.label :chronological_order, 'Chronological Order' %><br>
    <%= form.text_field :order %>
  </p>

  <p>
    <%= form.label :length, 'Length (minutes)' %><br>
    <%= form.text_field :length %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/movies/edit.html.erb
<%= link_to '<< All Movies', movies_path %>

<h1>Edit</h1>

<%= render 'form' %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Star Wars</h1>

<%= link_to 'Add New Movie', new_movie_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Release Date</th>
      <th>Chron. Order</th>
      <th>Length</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.release_date.strftime("%b %d, %Y") %></td>
        <td><%= movie.order %></td>
        <td><%= movie.length %> min</td>
        <td></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie_path(movie),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', controller: 'home' %>

app/views/movies/new.html.erb
<%= link_to '<< Back', movies_path %>

<h1>New Movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to '<< All Movies', movies_path %>

<h2>
  <%= @movie.title %>
</h2>
 
<p>
  <strong>Release Date:</strong>
  <%= @movie.release_date %>
</p>

<p>
  <strong>Chronological Order:</strong>
  <%= @movie.order %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<% if @movie.crawl.present? %>
	<p>
	  <strong>Opening Crawl:</strong>
  	  <%= @movie.crawl.text %>
  	</p>
<% end %>

<%= link_to 'Edit', edit_movie_path(@movie) %>